metadata:
  labels:
    team: Cloud_Self_Service
    project: vod-ms-customerInfo
    hystrix.enabled: true
    hystrix.cluster: default
    version: 1.0.0-SNAPSHOT
spec:
  type: ClusterIP
  ports:
      - port: 8080
        targetPort: 8080
