apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: vod-ms-customerInfo
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name:  vod-ms-customerInfo
  targetCPUUtilizationPercentage: 80
