---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: vod-ms-customerInfo
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: za.co.vodacom.ms.customerInfo
  name: vod-ms-customerInfo
spec:
  maxReplicas: 1
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: vod-ms-customerInfo
  targetCPUUtilizationPercentage: 80
